### ISSUE TITLE
Size different after watermark

### ISSUE THREAD

**Issue by iqbalmalik89** [chinmay235/php-pdf-watermark#2]
I see difference in size after watermarking pdf.

**Comment by chinmay235** [comment]
I have checked here is no any different size after watermarking PDF.

Could you please show me your PDF code?

**Comment by iqbalmalik89** [comment]
Here is the code.

https://gist.github.com/iqbalmalik89/dc8338b521b2ec11e91995f880888597

**Comment by chinmay235** [comment]
If you want to difference size then you should call `$this->SetFont()` of each line of watermark text.

See Code:

```
$this->SetFont('Arial', 'B', 20);
$this->RotatedText(20, 10, 'Instructor: Jason Bourne', 0);
$this->SetFont('Arial', 'B', 10);
$this->RotatedText(20, 15, 'Student: Rehan Malik', 0);
$this->SetFont('Arial', 'B', 16);
$this->RotatedText(140, 10, 'Date: 15 March 1989', 0);
$this->SetFont('Arial', 'B', 50);
$this->RotatedText(10, 25, 'Control Number: 20122', 0);
```
