### ISSUE TITLE
Exsiting PDF with url path not working

### ISSUE THREAD

**Issue by kuldeep1984** [chinmay235/php-pdf-watermark#3]
Hi, It is producing error when using uri path for pdf. Obviously the pdf is not in my current folder that can be access through URL only

**ERROR -** 

**Warning: fseek(): stream does not support seeking in C:\xampp\htdocs\ktest\old-fpdf\FPDI\pdf_parser.php on line 252

Warning: fseek(): stream does not support seeking in C:\xampp\htdocs\ktest\old-fpdf\FPDI\pdf_parser.php on line 283

Warning: fseek(): stream does not support seeking in C:\xampp\htdocs\ktest\old-fpdf\FPDI\pdf_parser.php on line 285

Fatal error: Uncaught Exception: Unable to find "startxref" keyword. in C:\xampp\htdocs\ktest\old-fpdf\FPDI\pdf_parser.php:296 Stack trace: #0 C:\xampp\htdocs\ktest\old-fpdf\FPDI\pdf_parser.php(204): pdf_parser->_findXref() #1 C:\xampp\htdocs\ktest\old-fpdf\FPDI\fpdi_pdf_parser.php(73): pdf_parser->__construct('http://localhos...') #2 C:\xampp\htdocs\ktest\old-fpdf\FPDI\fpdi.php(135): fpdi_pdf_parser->__construct('http://localhos...') #3 C:\xampp\htdocs\ktest\old-fpdf\FPDI\fpdi.php(113): FPDI->_getPdfParser('http://localhos...') #4 C:\xampp\htdocs\ktest\old-fpdf\watermark-edit-existing-pdf.php(57): FPDI->setSourceFile('http://localhos...') #5 C:\xampp\htdocs\ktest\old-fpdf\fpdf\fpdf.php(348): PDF->Header() #6 C:\xampp\htdocs\ktest\old-fpdf\FPDI\fpdf_tpl.php(376): FPDF->AddPage('', '') #7 C:\xampp\htdocs\ktest\old-fpdf\watermark-edit-existing-pdf.php(78): FPDF_TPL->AddPage() #8 {main} thrown in C:\xampp\htdocs\ktest\old-fpdf\FPDI\pdf_parser.php on line 296**

**Comment by chinmay235** [comment]
Hi @kuldeep1984 

we are sorry for late.

Could you please look below doc

https://manuals.setasign.com/fpdi-manual/v1/the-fpdi-class/#index-3-1

Stackoverflow
https://stackoverflow.com/questions/32271078/fpdf-error-unable-to-find-startxref-keyword
