### ISSUE TITLE
How Can use this as a function ?

### ISSUE THREAD

**Issue by pankajxenix** [chinmay235/php-pdf-watermark#6]
Hi,

I am try to use this in Drupal 8. I have pdf in which I want to add watermark. So I use watermark-edit-existing-pdf.php This code working fine. But for use this in Drupal cms I need to use this as function. Please suggest me How can I do this ?

**Comment by chinmay235** [comment]
Hi @pankajxenix ,
We have made some changes in our file. Could you please check and let us know if this is working for your Drupal CMS.
